DROP TABLE IF EXISTS Texts;
DROP TABLE IF EXISTS Lang;

CREATE TABLE Texts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT
);

CREATE TABLE Lang (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    language TEXT
);